### PR TITLE
Added a lookup method that uses an identifier to create an icon

### PR DESCRIPTION
**Pull request by GabrielCartier**
Issue was discussed in #53, the idea is to be able to create icons using the string identifiers associated with the icons.

I updated the generator scripts to automatically be able to generate the methods.

### CODE REVIEW

**Comment by GabrielCartier** [comment]
If you want, I can add the lookup method for the new icon sets taht were added

**Comment by PrideChung** [comment]
That would be lovely. I'm merging pull requests right now, let me finish first so you can start from clean state.

**Comment by PrideChung** [comment]
Thanks for your contribute, I just have time to review your code. The big if-else looks a little scary. I think we should use dictionary to do the name -> icon lookup. The design of `- allIcons` method on `FAKIcon` is flaw because I didn't foresee that there would be aliases. Maybe we should do it right this time. Add a dictionary to store the name -> unicode information, with that we can create an icon by it's name, and we can store both name and unicode in the icon instance,

**Comment by GabrielCartier** [comment]
I don't mind doing it that way, it makes sense to me. It should only require minor scripting. I would basically change the dictionary to have like "fa-star" : "unicode" ?

Do you like the syntax of the main method? If so, I'll just delete the PR and redo another one including the new icon generators. I can get it done by tomorrow.

**Comment by GabrielCartier** [comment]
Also @PrideChung what should the method return in case the name is invalid? Right now it returns nil, should I leave it like this?

**Comment by PrideChung** [comment]
@GabrielCartier I think we should add an inout `NSError` parameter to report the invalid name error, it will support Swift 2's new try-catch error handling model automatically.

**Comment by top2tech** [comment]
Thank you guys for your hardwork. 
A dictionary is great. Regarding invalid name handling, I'd suggest returning nil is easier for an app to use? Usually return value is easier to handle than inout parameter. No extra code is needed. and if it's nil, I may not do anything, the icon will just show as empty, which may be exactly what I want.

**Pull request closed without merging**
