### PR TITLE
Update Font Awesome 4.5 to Font Awesome 4.6 and add Carthage support

### PR DESCRIPTION
**Pull request by RemyDCF**
This pull request update Font Awesome to 4.6 version and add a Carthage support

### CODE REVIEW

**Comment by hy9be** [comment]
@PrideChung could you review this PR and see if you want to merge it? Thanks!

**Comment by hy9be** [comment]
@RemyDCF I run into errors
```
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, id:478AE865-1112-4DD6-AAB7-EE718E90D7A6 }

**Comment by hy9be** [comment]
Not quite sure but I suspect the problem is that you specified the deployment target to 10.0 in your xcodeproj file: https://github.com/PrideChung/FontAwesomeKit/pull/88/commits/3c2dc80791b778b68004a9a8330dc40ad78425b9#diff-4d794de573ae23cd89ba70c61fc73dd6R262
https://github.com/PrideChung/FontAwesomeKit/pull/88/commits/3c2dc80791b778b68004a9a8330dc40ad78425b9#diff-4d794de573ae23cd89ba70c61fc73dd6R307

**Comment by RemyDCF** [comment]
I created a new pull request ( #95 ). Does it work now ?

**Comment by hy9be** [comment]
@RemyDCF It works now on your fork.

**Pull request merged**
