### PR TITLE
Added a lookup method that uses an identifier to create an icon

### PR DESCRIPTION
**Pull request by GabrielCartier**
Issue was discussed in #53, the idea is to be able to create icons using the string identifiers associated with the icons. I added an error to fit the Swift structure. The error is set when identifier is not found in allIcons. 

I updated the generator scripts to automatically be able to generate the methods.

### CODE REVIEW

**Comment by GabrielCartier** [comment]
The readme file might need some modification based on PR #65

**Comment by top2tech** [comment]
looks like there are conflicts with master?

**Comment by GabrielCartier** [comment]
What are the conflicts?
How can I help?

**Comment by MontakOleg** [comment]
Gabriel, thanks for you work.

Below comments, there is 'branch has conflicts' badge

branch has conflicts

You should make pull from PrideChung:master, resolve conflicts and push to GabrielCartier:master. Then, PR can be merged.

**Comment by GabrielCartier** [comment]
Just pushed an update. I did the merge request with the latest version, everything is now merge-able.

Let me know if there is anything.

**Pull request merged**
